name: Build Search Index

on:
  push:
    branches: [ main ]
    paths: [ 'md/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'md/**' ]
  schedule:
    # 每天凌晨2点执行一次 (Runs at 2 AM every day)
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 授予 Job 推送代码的权限 (Grant the job permissions to push code)
    permissions:
      contents: write

    steps:
    # 步骤1: 检出仓库代码 (Step 1: Checkout repository code)
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # 使用 GITHUB_TOKEN 以便后续可以推送代码 (Use GITHUB_TOKEN to allow pushing code later)
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # 步骤2: 设置 Node.js 环境 (Step 2: Setup Node.js environment)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        # 根据 scripts 目录下的 lock 文件缓存依赖 (Cache dependencies based on the lock file in the scripts directory)
        cache-dependency-path: 'scripts/package-lock.json'
    
    # 步骤3: 安装依赖 (Step 3: Install dependencies)
    - name: Install dependencies
      run: |
        set -x # 开启调试模式，打印每条执行的命令 (Enable debug mode to print each command)
        echo "==> Entering 'scripts' directory..."
        cd scripts
        echo "==> Installing dependencies with 'npm ci'..."
        npm ci
    
    # 步骤4: 构建搜索索引 (Step 4: Build search index)
    - name: Build search index
      run: |
        set -x # 开启调试模式 (Enable debug mode)
        echo "==> Entering 'scripts' directory..."
        cd scripts
        echo "==> Running build script 'npm run build'..."
        npm run build
        
    # 步骤5: 查看生成的文件 (用于调试) (Step 5: Check generated files for debugging)
    - name: List generated files
      run: |
        set -x # 开启调试模式 (Enable debug mode)
        echo "==> Checking 'docs' directory contents..."
        ls -R docs
        
    # 新增步骤: 检查 Git 状态 (用于深度调试) (New Step: Check Git status for deep debugging)
    - name: Check git status
      run: |
        set -x
        git status

    # 步骤6: 提交并推送变更 (采用更稳定的专业 Action) (Step 6: Commit and push changes using a more stable and professional action)
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # 提交信息 (Commit message)
        commit_message: "Auto-update search index [skip ci]"
        # 要添加的文件模式，这里指定 data 目录下的所有文件 (File pattern to add, specifies all files under the data directory)
        file_pattern: docs/data/*
        # Git 用户名 (Git user name)
        commit_user_name: GitHub Action
        # Git 用户邮箱 (Git user email)
        commit_user_email: action@github.com
